[package]
name = "tauri-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "tauri_app"
path = "src/lib.rs"

[dependencies]
once_cell = "1.17" 